kor.far: kor.grm alfabet.txt ./dane/waga0/xaa ./dane/waga0/xab ./dane/waga0/xac ./dane/waga0/xad ./dane/waga0/xae ./dane/waga0/xaf ./dane/waga0/xag ./dane/waga0/xah ./dane/waga0/xai ./dane/waga0/xaj ./dane/waga-1.txt ./dane/waga-2.txt ./dane/waga-3.txt ./dane/waga-4.txt ./dane/waga-5.txt
	thraxcompiler --input_grammar=$< --output_far=$@

clean:
	rm -f 
