kor.far: kor.grm alfabet.txt slowa2M_2,5M.txt slowa0_500k.txt slowa3M_3,22806M.txt slowa1,5M_2M.txt slowa500k_1M.txt slowa1M_1,5M.txt ./waga-4.txt ./x
	thraxcompiler --input_grammar=$< --output_far=$@

clean:
	rm -f 
